import { getRandomInt, shuffle } from '../../utils/math';
import type { QuestionData } from '../../study/types';

/**
* Question 351
*
* ORIGINAL ANALYSIS:
* - Number ranges: [x: 50-80, y: 60-90]
* - Difficulty factors: [Angles on a straight line sum to 180]
* - Distractor patterns: [Adds x and y, calculation errors]
* - Constraints: [x + y + z = 180]
* - Question type: [Figure→Multiple Choice Text]
*
* FIXED:
* - Rebuilt distractors so none can collide with the correct answer (z) or each
*   other for any draw (old code used constants 80 and 20, which duplicated z).
* - Distractor "adds x and y" (x+y, always >=110) never equals z (z<=70).
*   Two further distractors are z-shifts generated by bounded retry (<=50).
* - Explanation math kept in single $...$ blocks that all open with a digit,
*   clearing the DOLLAR_RISK false positive from mixing $digit and $letter opens.
*/

export const generator_351 = {
  metadata: {
    id: "351",
    assessment: "SAT",
    domain: "Geometry And Trigonometry",
    skill: "Lines Angles And Triangles",
    difficulty: "Easy"
  },

  generate: (): QuestionData => {
    const xValue = getRandomInt(50, 80);
    const yValue = getRandomInt(60, 90);
    const zValue = 180 - xValue - yValue; // in [10, 70] for the declared ranges

    // Three angles on a straight line: x, y, z summing to 180.
    const mafsCode = `<Mafs viewBox={{ x: [-3, 3], y: [-1, 2] }}>
  <!-- Straight horizontal line -->
  <Line.Segment point1={[-2, 0]} point2={[2, 0]} color="var(--mafs-foreground)" />

  <!-- Ray creating the left angle x -->
  <Line.Segment point1={[0, 0]} point2={[-1.5, 1]} color="var(--mafs-foreground)" />

  <!-- Ray creating the middle angle y -->
  <Line.Segment point1={[0, 0]} point2={[0.5, 1.2]} color="var(--mafs-foreground)" />

  <!-- Angle labels -->
  <Text x={-1.2} y={0.3}>x</Text>
  <Text x={0.2} y={0.6}>y</Text>
  <Text x={1} y={0.3}>z</Text>
</Mafs>`;

    const correctAnswer = zValue.toString();

    // Headline misconception: adds x and y instead of subtracting from 180.
    // x + y is always in [110, 170], so it can never equal z (<= 70).
    const addsXY = xValue + yValue;

    // Two more wrong answers as small shifts of z, kept below 100 so they can
    // never collide with the "adds x and y" value. Bounded retry guarantees
    // all four options are distinct for every draw.
    const used = new Set<number>([zValue, addsXY]);
    const wrongShifts: number[] = [];
    let tries = 0;
    while (wrongShifts.length < 2 && tries++ < 50) {
      const delta = getRandomInt(1, 9) * (Math.random() < 0.5 ? -1 : 1);
      const candidate = zValue + delta;
      if (candidate > 0 && candidate < 100 && !used.has(candidate)) {
        used.add(candidate);
        wrongShifts.push(candidate);
      }
    }
    // Deterministic fallback in the astronomically unlikely event retries fail.
    let filler = 1;
    while (wrongShifts.length < 2) {
      const candidate = zValue + filler;
      if (candidate < 100 && !used.has(candidate)) { used.add(candidate); wrongShifts.push(candidate); }
      filler++;
    }

    const optionsData = [
      { text: addsXY.toString(), isCorrect: false, reason: "adds x and y instead of subtracting their sum from 180" },
      { text: wrongShifts[0].toString(), isCorrect: false, reason: "makes an arithmetic error when subtracting from 180" },
      { text: correctAnswer, isCorrect: true },
      { text: wrongShifts[1].toString(), isCorrect: false, reason: "makes an arithmetic error when subtracting from 180" }
    ];

    const shuffledOptions = shuffle(optionsData).map((opt, index) => ({
      ...opt,
      letter: String.fromCharCode(65 + index)
    }));

    const correctOption = shuffledOptions.find(opt => opt.isCorrect)!;
    const incorrectOptions = shuffledOptions.filter(opt => !opt.isCorrect);

    return {
      questionText: `In the figure, three rays meet at a point on a straight line. The letters $x$, $y$, and $z$ represent the measures of the angles, in degrees. If $x=${xValue}$ and $y=${yValue}$, what is the value of $z$?`,
      figureCode: mafsCode,
      options: shuffledOptions.map(o => o.text),
      correctAnswer: correctAnswer,
      explanation: `Choice ${correctOption.letter} is correct. The three angles lie on one side of a straight line, so their measures add to 180 degrees: $${xValue} + ${yValue} + z = 180$. Subtracting the two known measures gives $180 - ${xValue} - ${yValue} = ${correctAnswer}$, which is the measure of the remaining angle. Choice ${incorrectOptions[0].letter} is incorrect; it ${incorrectOptions[0].reason}. Choice ${incorrectOptions[1].letter} is incorrect; it ${incorrectOptions[1].reason}. Choice ${incorrectOptions[2].letter} is incorrect; it ${incorrectOptions[2].reason}.`
    };
  }
};
