import { getRandomInt } from '../../utils/math';
import type { QuestionData } from '../../types';

/**
 * Question ID: e8f9e117
 * Skill: Linear Inequalities In One Or Two Variables
 * Difficulty: Hard
 * 
 * Description: Ohm's Law application with inequality constraints.
 * Fixes:
 * - Fixed "frac" rendering error by using correct escape sequence (`\\frac`).
 * - Formatted explanation math blocks.
 */
export const generator_e8f9e117 = {
  metadata: {
    assessment: "SAT",
    domain: "Algebra",
    skill: "Linear Inequalities In One Or Two Variables",
    difficulty: "Hard"
  },
  
  generate: (): QuestionData => {
    // ----------------------------------------------------------------------
    // 1. GENERATE VALUES
    // ----------------------------------------------------------------------
    const resistance = getRandomInt(4, 6) * 100; // 400 - 600
    const batteryVoltage = getRandomInt(4, 9);   // 4V - 9V
    const maxCurrent = getRandomInt(20, 30) / 100; // 0.20A - 0.30A
    
    // ----------------------------------------------------------------------
    // 2. MATHEMATICAL LOGIC
    // ----------------------------------------------------------------------
    // Ohm's Law: I = V / R
    // V_total = n * batteryVoltage
    // Constraint: I <= maxCurrent
    // (n * batteryVoltage) / resistance <= maxCurrent
    // n <= (maxCurrent * resistance) / batteryVoltage
    
    const limit = (maxCurrent * resistance) / batteryVoltage;
    const maxN = Math.floor(limit);

    // ----------------------------------------------------------------------
    // 3. RETURN DATA
    // ----------------------------------------------------------------------
    return {
      // Note: Use \\frac for fraction, not \\\\frac
      questionText: `The formula $I = \\frac{V}{R}$ is Ohm's law for an electric circuit with current $I$, in amperes, potential difference $V$, in volts, and resistance $R$, in ohms. A circuit has a resistance of $${resistance}$ ohms, and its potential difference will be generated by $n$ ${batteryVoltage}-volt batteries that produce a total potential difference of $${batteryVoltage}n$ volts. If the circuit is to have a current of no more than $${maxCurrent}$ amperes, what is the greatest number, $n$, of ${batteryVoltage}-volt batteries that can be used?`,
      figureCode: null,
      options: null, // Fill-in-the-blank
      correctAnswer: maxN.toString(),
      explanation: `
        The correct answer is ${maxN}.
        <br/><br/>
        We are given Ohm's law $I = \\frac{V}{R}$ and the constraint that $I \\le ${maxCurrent}$.
        <br/><br/>
        1. <b>Substitute the known values:</b>
        $R = ${resistance}$
        $V = ${batteryVoltage}n$
        <br/>
        2. <b>Set up the inequality:</b>
        $$ \\frac{${batteryVoltage}n}{${resistance}} \\le ${maxCurrent} $$
        <br/>
        3. <b>Solve for $n$:</b>
        Multiply both sides by $${resistance}$:
        $$ ${batteryVoltage}n \\le ${maxCurrent} \\times ${resistance} $$
        $$ ${batteryVoltage}n \\le ${maxCurrent * resistance} $$
        <br/>
        Divide by $${batteryVoltage}$:
        $$ n \\le \\frac{${maxCurrent * resistance}}{${batteryVoltage}} $$
        $$ n \\le ${limit.toFixed(2)} $$
        <br/>
        Since $n$ must be a whole number of batteries, the greatest possible value is ${maxN}.
      `
    };
  }
};